apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: ghcr.io/yogendra/blue-green:latest
          name: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: CONFIG_JSON
              valueFrom:
                configMapKeyRef:
                  key: "config.json"
                  name: client
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
data:
  config.json: |
    {
      "port": 3001,
      "endpoint": {
        "type": "dns",
        "address": "echo-server.apps.acepod.com",
        "nameservers": ["10.10.10.101","10.10.20.101"],
        "versionMap": {
          "10.10.10.103": "blue",
          "10.10.20.104": "green"
        }
      },
      "probe": {
        "interval": 10
      },
      "sample": {
        "interval": 1000,
        "max": 600
      },
      "graph": {
        "colors": ["blue", "green"]
      }
    }

---
kind: Service
apiVersion: v1
metadata:
  name: client
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client
  labels:
    name: client
    app: avi-gslb
spec:
  ingressClassName: openshift-default
  tls:
    - secretName: client-ingress-tls
      hosts:
        - client.apps.acepod.com
  rules:
    - host: client.apps.acepod.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: client
                port:
                  name: http
---
